#!/usr/bin/python3
import os
from sys import argv
from funcs import main, preference
if __name__ == '__main__':
    VERSION = '0.1.2'
    if len(argv) != 1:
        if argv[1] == '--clear':
            print("Successful!")
            os.system("rm -rf ./config/setup.ini")
        elif argv[1] == '--help':
            print(f"用法: {argv[0]} [选项]")
            print("选项: ")
            print(f"--clear\t\t清理用户配置选项")
            print(f"--help\t\t显示帮助")
            print(f"--preference\t显示【首选项】页面")
            print(f"--repair\t解决脚本目录下权限不足的问题")
            print(f"--version\t显示当前版本号")
        elif argv[1] == '--preference':
            preference.main("./config/setup.ini")
        elif argv[1] == '--repair':
            os.system("chmod u+x ./scripts/*.sh")
            print("Successful!")
        elif argv[1] == '--version':
            print(f"Shell Toolbox version {VERSION}")
            print(f"作者: CatIsNotFound")
            print(f"获取更新? 请访问: https://github.com/CatIsNotFound/ShellToolbox/releases")
        else:
            print(f"未知的选项: {argv[1]}")
            print(f"尝试执行: {argv[0]} --help")
        # pass
    else:
        main.start(VERSION)
