#!/bin/bash
# Fcitx 4 / Fcitx 5 安装与卸载

function setup_fcitx() {
    echo "正在启动 $1..."
    $1 -d &> /dev/null
    read -p "是否需要打开配置工具? 等待 5 秒或按任意键以跳过此项. (yes) " -t 5 OPT
    if [[ $OPT == 'yes' ]];then
        echo "正在打开配置工具..."
        $1-configtool
    fi
    echo -n "正在写入环境变量..."
    cat > $HOME/.bash_profile << EOF
# Auto-generated by scripts.
export GTK_IM_MODULE=$1
export XMODIFIERS=$1
export QT_IM_MODULE=$1
$1 -d &> /dev/null
EOF
    sleep 1s
    echo -e "已安装与配置 $1, 请\033[1m手动注销并重新登录桌面\033[0m."
    echo -e "\033[33m注意: 按下 \033[1mCtrl + Alt + Delete\033[0m\033[33m 以手动注销并重新登录以生效配置.\033[0m "
    read -p "请按任意键以结束..."
    exit 0
}

function install_fcitx() {
    echo -e "\033[1m正在准备下载安装 $1...\033[0m"
    echo -e "\033[1;31m注意: 请输入用户密码以确认执行操作!\033[0m"
    sudo echo -e "\033[1m:已提权:\033[0m"
    if [ $? -ne 0 ];then
        exit 1
    fi
    echo "正在更新软件源..."
    sudo apt-get update > /dev/null
    
    if [[ $1 == 'fcitx' ]];then
        echo -e "正在下载安装 \033[1m$1\033[0m..."
        sudo apt-get install fcitx fcitx-sunpinyin fcitx-pinyin fcitx-rime -y
    elif [[ $1 == 'fcitx5' ]];then
        echo -e "正在下载安装 \033[1m$1\033[0m..."
        sudo apt-get install fcitx5 fcitx5-chinese-addons fcitx5-rime -y
    fi
    if [ $? -ne 0 ];then
        echo "Error: 无法安装或找不到软件包! "
        read -p "请按任意键以结束执行."
        exit 1
    fi
}

function remove_fcitx() {
    echo -e "\033[1m正在准备移除 $1...\033[0m"
    echo -e "\033[1;31m注意: 请输入用户密码以确认执行操作!\033[0m"
    sudo echo -e "\033[1m:已提权:\033[0m"
    if [ $? -ne 0 ];then
        exit 1
    fi
    echo "正在关闭 $1..."
    if [[ $1 == 'ibus' ]];then
        ibus exit
    else
        $1-remote -e
    fi
    echo "" > $HOME/.bash_profile 
    sleep 1s
    echo "正在移除 $1..."
    sudo apt-get purge $1 -y
    if [ $? -ne 0 ];then
        sudo rm -rf /var/lib/dpkg/lock*
        sleep 1s
        sudo apt-get purge $1 -y
    fi
    sudo apt-get autoremove -y
    echo "已彻底移除 $1"
}

function check_installed() {
    if [ -f /usr/bin/$1 ];then
        echo "检查到当前系统上已安装 $1, 是否选择卸载? "
        echo "注意: Fcitx, Fcitx 5, ibus 不能同时安装."
        read -p "卸载? (y/n) " opt
        if [[ $opt == 'y' || $opt == 'Y' ]];then
            remove_fcitx $1
            return 1
        else
            exit 1
        fi
    fi
    return 0
}

check_installed ibus
if [[ $1 == 'fcitx5' ]];then
    check_installed fcitx
    if [ $? -eq 1 ];then
        install_fcitx $1
        setup_fcitx $1
    fi
elif [[ $1 == 'fcitx' ]];then
    check_installed fcitx5
    if [ $? -eq 1 ];then
        install_fcitx $1
        setup_fcitx $1
    fi
fi

if [ ! -f /usr/bin/$1 ];then
    sleep 1s
    install_fcitx $1
    setup_fcitx $1
fi

echo "需要对 $1 做什么？(选择数字键)"
select OPT in 更新 配置 重启 卸载 退出; do
    case $OPT in
        更新)
            install_fcitx $1
            ;;
        配置)
            read -p "需要打开配置工具吗? (y/n) " OPT
            if [[ $OPT == 'y' ]];then
                echo "正在打开配置工具..."
                $1-configtool
            fi
            read -p "需要打开输入法配置吗? (y/n) " OPT
            if [[ $OPT == 'y' ]];then
                echo "正在打开输入法配置..."
                im-config
            fi
            ;;
        重启)
            echo "正在重启 $1..."
            $1-remote -e
            sleep 2s
            $1 -d
            $1-remote -a
            echo "已完成重启! "
            ;;
        卸载)
            read -p "是否确认卸载 $1? 输入 yes 确认卸载. (yes) " OPT
            if [[ $OPT == 'yes' ]];then
                remove_fcitx $1
            fi
            sleep 1s
            exit 0
            ;;
        退出)
            exit 0
            ;;
    esac
done

