#!/bin/bash
# Fcitx 4 / Fcitx 5 安装与卸载

function setup_fcitx() {
    echo "正在启动 $1..."
    $1 -d > /dev/null
    echo -e "\033[1m注意: 第一次启动需要添加输入法才能正常切换. \033[0m"
    echo "即将打开配置工具..."
    sleep 3s
    $1-configtool
    echo -n "正在写入环境变量..."
    cat > $HOME/.pam_environment << EOF
# Auto-generated by scripts.
export GTK_IM_MODULE=$1
export XMODIFIERS=$1
export QT_IM_MODULE=$1
$1 -d &> /dev/null
EOF
    cat $HOME/.bashrc | grep pam_environment
    if [ $? -ne 0 ];then
            echo "..."
            cat >> $HOME/.bashrc << EOF
./pam_environment &> /dev/null
EOF
    fi
    sleep 1s
    echo -e "\033[33m注意: 请按下 \033[1mCtrl + Alt + Delete\033[0m\033[33m 以注销当前用户并重新登录以生效配置.\033[0m "
    read -p "请按任意键以结束..."
    exit 0
}

function install_fcitx() {
    echo -e "\033[1m正在准备下载安装 $1...\033[0m"
    echo -e "\033[1;31m注意: 请输入用户密码以确认执行操作!\033[0m"
    sudo echo -e "\033[1m:已提权:\033[0m"
    if [ $? -ne 0 ];then
        exit 1
    fi
    echo "正在更新软件源..."
    sudo apt-get update > /dev/null
    echo -e "正在下载安装 \033[1m$1\033[0m..."
    if [[ $1 == 'fcitx' ]];then
        sudo apt-get install fcitx fcitx-sunpinyin fcitx-pinyin fcitx-rime -y
    elif [[ $1 == 'fcitx5' ]];then
        sudo apt-get install fcitx5 fcitx5-chinese-addons fcitx5-rime -y
    fi
    if [ $? -ne 0 ];then
        echo "Error: 无法安装或找不到软件包! "
        read -p "请按任意键以结束执行."
        exit 1
    fi
    setup_fcitx $1
}

function remove_fcitx() {
    echo -e "\033[1m正在准备移除 $1...\033[0m"
    echo -e "\033[1;31m注意: 请输入用户密码以确认执行操作!\033[0m"
    sudo echo -e "\033[1m:已提权:\033[0m"
    if [ $? -ne 0 ];then
        exit 1
    fi
    echo "正在关闭 $1..."
    sudo killall $1
    sleep 1s
    echo "正在移除 $1..."
    sudo apt-get purge $1 -y
    sudo apt-get autoremove -y
    echo "已彻底移除 $1"
}

function check_installed() {
    if [ -f /usr/bin/$1 ];then
        echo "检查到当前系统上已安装 $1, 是否选择卸载? "
        echo "注意: Fcitx 与 Fcitx 5 不能同时安装."
        read -p "卸载? (y/n) " opt
        if [[ $opt == 'y' || $opt == 'Y' ]];then
            remove_fcitx $1
            return 1
        else
            exit 1
        fi
    fi
    return 0
}

if [[ $1 == 'fcitx5' ]];then
    check_installed fcitx
    if [ $? -eq 1 ];then
        install_fcitx $1
    fi
elif [[ $1 == 'fcitx' ]];then
    check_installed fcitx5
    if [ $? -eq 1 ];then
        install_fcitx $1
    fi
fi

check_installed $1
if [ $? -eq 0 ];then
    read -p "当前系统上并未安装 $1, 是否确认安装? (yes) " opt
    if [[ $opt == 'yes' ]];then
        install_fcitx $1
    fi
fi


